Repository hatchways/team-dragonfruit, pull requests merged in 2020-07, with the labels that each got.

#14 Initial implementation of backend auth
  package-lock.json
  server/app.js
  server/bin/www
  server/db/mongoose.js
  server/middleware/auth.js
  server/models/snippet.js
  server/models/user.js
  server/package-lock.json
  server/package.json
  server/routes/user.js
Labels: new feature

#15 Update README.md
  README.md
Labels: documentation

#17 Fe dashboard navbar
  client/package-lock.json
  client/package.json
  client/public/avatar1.png
  client/public/index.html
  client/src/App.css
  client/src/App.js
  client/src/images/avatar1.png
  client/src/images/logo.png
  client/src/images/project1.png
  client/src/images/project2.png
  client/src/pages/Balance.js
  client/src/pages/Navbar.js
  client/src/pages/Profile.js
  client/src/pages/Reviews.js
  client/src/pages/Upload.js
  client/src/setupProxy.js
  client/src/themes/theme.js
  client/src/utilities/Avatar.js
  client/src/utilities/BadgeMenu.js
  client/src/utilities/NavbarMenu.js
  client/src/utilities/ProjectCard.js
Labels: new feature

#34 Fe editor
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/App.js
  client/src/prism.css
  client/src/utils/CodeReader.js
  client/src/utils/Editor.js
  client/src/utils/NavbarMenu.js
  client/src/utils/PrismDraft.js
  client/src/utils/UploadDialog.js
  client/src/utils/validateUpload.js
  server/models/snippet.js
  server/routes/snippet.js
Labels: enhancement

#33 added review skeleton
  client/src/App.js
  client/src/components/Review.js
  client/src/components/ReviewDetails.js
  client/src/components/ReviewList.js
  client/src/context/AuthContext.js
  client/src/images/avatar2.png
  client/src/pages/Reviews.js
  client/src/utils/NavbarMenu.js
  server/models/snippet.js
Labels: new feature

#44 Fs onboarding
  client/src/App.css
  client/src/App.js
  client/src/components/LanguageRenderer.js
  client/src/components/NewOnboarding.js
  client/src/components/Onboarding.js
  client/src/components/UploadAvatar.js
  client/src/pages/EditProfile.js
  client/src/pages/Navbar.js
  client/src/pages/Profile.js
  client/src/utils/DropeZone.js
  client/src/utils/NavbarMenu.js
  client/src/utils/UploadDialog.js
  client/src/utils/validateUpload.js
  server/models/user.js
  server/package-lock.json
  server/package.json
  server/routes/user.js
Labels: enhancement

#54 Fs avatar
  client/src/pages/EditProfile.js
  server/models/user.js
  server/routes/user.js
Labels: new feature
